#!/bin/bash

lshift=34
rshift=4

files=(~/Documents/quickdocs/*)

if [ $# -ge 1 ]
then
	if [ $# -ge 2 ]
	then 
		if [ $2 == "-e" ]
		then 
			vim ${files[${1}-1]}
		fi
	else
		cat ${files[${1}-1]}
	fi
	exit
else
	echo "Quick Document Files:"
	for((i=1; i<=${#files[@]}; i++))
	do
		temp="${files[i-1]:$lshift}"
		echo "  [${i}] ${temp:0:${#temp}-$rshift}"
	done
fi
