#!/bin/bash

lshift=34
rshift=4

center() {
  termwidth="$(tput cols)"
  padding="$(printf '%0.1s' ={1..500})"
  printf '%*.*s %s %*.*s\n' 0 "$(((termwidth-2-${#1})/2))" "$padding" "$1" 0 "$(((termwidth-1-${#1})/2))" "$padding"
}

files=(~/Documents/quickdocs/*)

if [ $# -ge 1 ]
then
	if [ $# -ge 2 ]
	then 
		if [ $2 == "-e" ]
		then 
			vim ${files[${1}-1]}
		fi
	else
		clear 
		temp="${files[${1}-1]:$lshift}"
		center "${temp:0:${#temp}-$rshift}"
		cat ${files[${1}-1]}
	fi
	exit
else
	echo "Quick Document Files:"
	for((i=1; i<=${#files[@]}; i++))
	do
		temp="${files[i-1]:$lshift}"
		echo "  [${i}] ${temp:0:${#temp}-$rshift}"
	done
fi
