#!/bin/bash

path=~/Documents/quickdocs/todo.txt

clear
if [ $# -ge 1 ]
then
	if [ $1 == "-f" ]
	then 
		cat $path
	else
		nvim $path
		sed -n '/-------------- Queue ---------------/!p;//q' $path
	fi
else
	sed -n '/-------------- Queue ---------------/!p;//q' $path
fi

